### ISSUE TITLE
Unstable feature warning

### ISSUE THREAD

**Issue by foodelevator** [inda21plusplus/thstro-chess#1]
At [`src/lib.rs:38`](https://github.com/inda21plusplus/thstro-chess/blob/a64705dd29c92d195c2c191d4baa98cccd8f5acc/src/lib.rs#L38) you activate a warning for unstable features, then at [`src/lib.rs:56`](https://github.com/inda21plusplus/thstro-chess/blob/a64705dd29c92d195c2c191d4baa98cccd8f5acc/src/lib.rs#L56) you use an unstable feature.

I would suggest you remove either one of them.

**Comment by TerraDOOM** [comment]
[Fixed](https://github.com/inda21plusplus/thstro-chess/commit/fd5f2ec815bc3304589d7f976a5c249128777dc6)

**Comment by TerraDOOM** [comment]
[Fixed](https://github.com/inda21plusplus/thstro-chess/commit/fd5f2ec815bc3304589d7f976a5c249128777dc6)
